const extensionToFileTypeMapper = {
    'js': 'javascript',
    'jsx': 'javascript',
    'ts': 'typescript',
    'tsx': 'typescript',
    'html': 'html',
    'css': 'css',
    'scss': 'scss',
    'json': 'json',
    'md': 'markdown',
    'txt': 'plaintext',
    'py': 'python',
    'java': 'java',
    'c': 'c',
    'cpp': 'cpp',
    'cs': 'csharp',
    'php': 'php',
    'sql': 'sql',
    'swift': 'swift',
    'rb': 'ruby',
    'go': 'go',
    'kt': 'kotlin',
    'vue': 'vue',
    'svelte': 'svelte',
    'rb': 'ruby',
    'sh': 'shell',
    'ps1': 'powershell',
    'psm1': 'powershell',
    'psd1': 'powershell',
    'ps1xml': 'powershell',
    'psc1': 'powershell',
    'psc2': 'powershell',
    'dsc': 'powershell',
    'mof': 'powershell',
    'xml': 'xml',
    'yaml': 'yaml',
    'yml': 'yaml',
    'toml': 'toml',
    'ini': 'ini',
    'env': 'env',
    'svg': 'svg',
    'jpeg': 'jpeg',
    'jpg': 'jpg',
    'png': 'png',
    'gif': 'gif',
    'webp': 'webp',
    'ico': 'ico',
    'bmp': 'bmp',
    'tiff': 'tiff',
    'tif': 'tif',
}

export const extensionToFileType = (extension) => {
    if (!extension) return undefined;
    return extensionToFileTypeMapper[extension];
}